platform :ios, '14.0'

target 'WorkTimeManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SnapKit', '~> 5'
pod 'SwiftLint', '~> 0'
pod 'R.swift', '~> 7'

pod 'UIComponents', :path => './Frameworks/UIComponents'
pod 'AuthSDK', :path => './Frameworks/AuthSDK'

  # Pods for WorkTimeManager

end
