# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'WorkTimeManager' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SnapKit', '~> 5'

  # Pods for WorkTimeManager

end